"""empty message

Revision ID: 53c39fe12f71
Revises: d14592e6d925
Create Date: 2021-08-19 16:56:36.341035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53c39fe12f71'
down_revision = 'd14592e6d925'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('turn_off_commenting', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'turn_off_commenting')
    # ### end Alembic commands ###
