"""empty message

Revision ID: 5a1e7bcc4be4
Revises: 9077247c67f4
Create Date: 2021-08-19 21:35:41.015878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a1e7bcc4be4'
down_revision = '9077247c67f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('community_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=25), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('community_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('community_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['community_id'], ['community.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('community_member', sa.Column('role_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'community_member', 'community_role', ['role_id'], ['id'])
    op.drop_column('community_member', 'is_admin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('community_member', sa.Column('is_admin', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'community_member', type_='foreignkey')
    op.drop_column('community_member', 'role_id')
    op.drop_table('community_post')
    op.drop_table('community_role')
    # ### end Alembic commands ###
