"""empty message

Revision ID: 777467e0b1cb
Revises: e7f49c29addc
Create Date: 2021-08-20 15:37:48.982330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '777467e0b1cb'
down_revision = 'e7f49c29addc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('community_post', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('community_post', sa.Column('title', sa.String(length=100), nullable=False))
    op.add_column('community_post', sa.Column('date_posted', sa.DateTime(), nullable=False))
    op.add_column('community_post', sa.Column('content', sa.Text(), nullable=False))
    op.add_column('community_post', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('community_post', sa.Column('turn_off_commenting', sa.Boolean(), nullable=True))
    op.alter_column('community_post', 'community_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('community_post_post_id_fkey', 'community_post', type_='foreignkey')
    op.create_foreign_key(None, 'community_post', 'user', ['user_id'], ['id'])
    op.drop_column('community_post', 'post_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('community_post', sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'community_post', type_='foreignkey')
    op.create_foreign_key('community_post_post_id_fkey', 'community_post', 'post', ['post_id'], ['id'])
    op.alter_column('community_post', 'community_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('community_post', 'turn_off_commenting')
    op.drop_column('community_post', 'user_id')
    op.drop_column('community_post', 'content')
    op.drop_column('community_post', 'date_posted')
    op.drop_column('community_post', 'title')
    op.drop_column('community_post', 'id')
    # ### end Alembic commands ###
