"""empty message

Revision ID: 799b04467908
Revises: 53c39fe12f71
Create Date: 2021-08-19 20:50:59.340669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '799b04467908'
down_revision = '53c39fe12f71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visibility',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=25), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('community',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('visibility_id', sa.Integer(), nullable=True),
    sa.Column('restrict_posting', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['visibility_id'], ['visibility.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_community_name'), 'community', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_community_name'), table_name='community')
    op.drop_table('community')
    op.drop_table('visibility')
    # ### end Alembic commands ###
