"""empty message

Revision ID: 94dc10e40739
Revises: 777467e0b1cb
Create Date: 2021-08-20 16:01:47.774827

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '94dc10e40739'
down_revision = '777467e0b1cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('community_post', sa.Column('post_id', sa.Integer(), nullable=False))
    op.alter_column('community_post', 'community_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('community_post_user_id_fkey', 'community_post', type_='foreignkey')
    op.create_foreign_key(None, 'community_post', 'post', ['post_id'], ['id'])
    op.drop_column('community_post', 'date_posted')
    op.drop_column('community_post', 'id')
    op.drop_column('community_post', 'turn_off_commenting')
    op.drop_column('community_post', 'content')
    op.drop_column('community_post', 'title')
    op.drop_column('community_post', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('community_post', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('community_post', sa.Column('title', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('community_post', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('community_post', sa.Column('turn_off_commenting', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('community_post', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('community_post', sa.Column('date_posted', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'community_post', type_='foreignkey')
    op.create_foreign_key('community_post_user_id_fkey', 'community_post', 'user', ['user_id'], ['id'])
    op.alter_column('community_post', 'community_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('community_post', 'post_id')
    # ### end Alembic commands ###
