"""empty message

Revision ID: bf9cb6a6f61c
Revises: 94dc10e40739
Create Date: 2021-08-20 21:59:01.158058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf9cb6a6f61c'
down_revision = '94dc10e40739'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('community_member', sa.Column('invited', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('community_member', 'invited')
    # ### end Alembic commands ###
